language: c

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq --no-install-recommends libwww-perl devscripts
    - uscan --force-download --rename
    - sudo apt-get purge -qq libwww-perl
    - sudo apt-get install -qq --no-install-recommends devscripts debhelper php5-dev dpatch

script:
    - debuild -uc -us

#notifications:
#  email: false
