language: c

before_install:
    # add newer (5.4) php version to source list
    - sudo add-apt-repository -y ppa:ondrej/php5-oldstable
    # update package list
    - sudo apt-get update -qq
    # installneeded packages for uscan
    - sudo apt-get install -qq --no-install-recommends devscripts libwww-perl
    # download original tarball
    - uscan --force-download
    # remove packages needed for uscan
    - sudo apt-get purge -qq libwww-perl
    - sudo apt-get autoremove -qq

install:
    # install build dependencies
    - sudo apt-get install -qq --no-install-recommends devscripts equivs
    - sudo mk-build-deps --install debian/control

script:
    # build the debian package
    - debuild -uc -us

#notifications:
#  email: false
